name: Unity-Builds

on:
  push:
    branches:
      [ main ]

jobs:

# Stage 1: Game Building
  buildAndTestForWebGL:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.6f1
        targetPlatform:
          - WebGL # WebGL.

    steps:

    # Checkout For WebGL
    - name: Checkout For WebGL
      uses: actions/checkout@v2
      with:
        lfs: true

    # Cache
    - name: Cache For WebGL
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-

    # Build For WebGL
    - name: Build For WebGL
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: ${{ matrix.targetPlatform }}

    - name: Upload Artifact For WebGL
      uses: actions/upload-artifact@v2
      with:
        name: build-WebGL
        path: build


# Stage 2: Game Deployment
  deployWebGLToGhPages:
    needs: [ buildAndTestForWebGL ]
    name: Deploy to Github-Pages
    runs-on: ubuntu-latest
    steps:

      # Download WebGL Artifact
      - name: Download WebGL Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-WebGL

      # Deploy WebGL Artifact
      - name: Deploy WebGL Artifact
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: github-pages
          folder: build