name: Unity-Builds

on:
  push:
    branches:
      [ main ]

jobs:

# Stage 1: Game Building
  buildForWebGL:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.6f1
        targetPlatform:
          - WebGL # WebGL.

    steps:

    # Checkout For WebGL
    - name: Checkout For WebGL
      uses: actions/checkout@v2
      with:
        lfs: true

    # Cache
    - name: Cache For WebGL
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-

    # Build For WebGL
    - name: Build For WebGL
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: ${{ matrix.targetPlatform }}

    - name: Upload Artifact For WebGL
      uses: actions/upload-artifact@v2
      with:
        name: build-WebGL
        path: build/${{ matrix.targetPlatform }}
    
    # Deploy WebGL
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: github-pages
        build_dir: build/${{ matrix.targetPlatform }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  buildForMacOS:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.6f1
        targetPlatform:
          - StandaloneOSX # Standalone macOS.

    steps:

    # Checkout For MacOS
    - name: Checkout For MacOS
      uses: actions/checkout@v2
      with:
        lfs: true
    
    # Cache
    - name: Cache For MacOS
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-
    
    # Build For MacOS
    - name: Build For MacOS
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: ${{ matrix.targetPlatform }}

    - name: Upload Artifact For MacOS
      uses: actions/upload-artifact@v2
      with:
        name: build-MacOS
        path: build
